version: "3"

services:
  scmmain:
    image: scmmain:latest
    restart: always
    environment:
      MONGO_URI: mongodb+srv://SCM:SCM123@scm.exqmgcq.mongodb.net/SCM?retryWrites=true&w=majority
    ports:
      - 8080:8080

  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - 2182:2181

    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:3.2
    ports:
      - 9093:9092

    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes

    depends_on:
      - zookeeper

  sockets:
    image: scmserver
    ports:
      - 12345:12345

  producer:
    image: scmproducer:v1
    restart: always
    environment:
      TOPIC_NAME: devicedata
      BOOTSTRAP_SERVERS: kafka:9092
      SOCKET_PORT: 12345
    depends_on:
      - kafka
    ports:
      - 8081:8081

  consumer:
    image: scmconsumer:v1
    # previous of local
    # newlocalconsumer:latest
    environment:
      MONGODB_URI: mongodb+srv://SCM:SCM123@scm.exqmgcq.mongodb.net/SCM?retryWrites=true&w=majority
      MONGO_DATABASE: SCM
      MONGO_COLLECTION: Stream
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: group-id
      TOPIC_NAME: devicedata
    depends_on:
      - kafka
    ports:
      - 8082:8082
